# Generated by Django 5.2.6 on 2025-09-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="Product",
            new_name="Product_id",
        ),
    ]
