# Generated by Django 5.2.6 on 2025-09-23 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_rename_product_cart_product_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="Product_id",
            new_name="Product",
        ),
    ]
