# Generated by Django 5.2.6 on 2025-09-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_rename_product_id_cart_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="Product",
            new_name="product",
        ),
    ]
